import localFont from "next/font/local";
import "./globals.css";
import Header from "./common/Header";
import Footer from "./common/Footer";
import ContextManege from "./context/ContextManege";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ContextManege>

          <Header />
          {children}

          <Footer />
        </ContextManege>
      </body>
    </html>
  );
}
